### ISSUE TITLE
Decrease Bundle Size for Templates

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-cli-templates#41]
#### Describe the bug
Auth Template (probably more) are over budget when building inside the context of a freshly generated angular v12 project.  The bundle size needs to be less than 1MB.  Perform some bundle analysis to identify the largest libraries & minimize bundle size.

#### What is the expected behavior?
Bundles are less than 1MB.

#### What are the steps to reproduce?
Generate a new project using @pxblue/cli.  Run yarn build & observe errors due to large bundle size.

**Comment by ektasawant** [comment]
Created Jira story PXBLUE-2675
