### ISSUE TITLE
Default each Auth Page as a Custom Ng Template

### ISSUE THREAD

**Issue by emclaug2** [pxblue/angular-cli-templates#8]
#### Describe the desired behavior
I want the generated auth component to use templateRefs for each page by default.  This will make adding individual page customizations easier. 

#### Describe the current behavior
The auth template uses default auth pages.  If a user wants to make a customization, they will have to define the template refs themselves and it'll take more effort than if the templateRefs were already being used.  

#### Is this request related to a current issue?
No

**Comment by jeffvg** [comment]
this does not need a fix. A different approach was used
